### ISSUE TITLE
Notes Issues

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#13]
When i added a note to the number and the note is marked as notification. When the call is received from the same number the existing notes notification is not displayed.
![note issue](https://user-images.githubusercontent.com/25291469/53143508-489fc780-35be-11e9-9996-e10bc0b13c9d.png)

**Comment by murugancmi** [comment]
This is not in stage still now

**Comment by murugancmi** [comment]
It's in stage now please check

**Comment by prasathsekar** [comment]
No the issue is not Fixed. Unable to add note.
![addnote](https://user-images.githubusercontent.com/25291469/53348569-526c5680-3941-11e9-9db1-2e990398a383.png)
