### ISSUE TITLE
Saved Contact Details Error in Log

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#15]
When i saved a number as contact,  it is saved in the dashboard.  When i try to call again the existing saved contact is not displaying. Instead it shows only the number.
![call details](https://user-images.githubusercontent.com/25291469/53146617-ebf6d980-35ca-11e9-995f-77a70a1abe60.png)

**Comment by murugancmi** [comment]
This is feature not in stage till now

**Comment by murugancmi** [comment]
It's in stage now please check
