### ISSUE TITLE
Callflow_track_plusicon

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#21]
Change the plus icon to be non-clickable. if i click the plus icon, it doesn't do anything.
![non-clickable-plus](https://user-images.githubusercontent.com/25261710/53339332-14b10300-392c-11e9-9ec4-4644d1550d1b.png)

**Comment by prabhutelecmi** [comment]
Now the mouse pointer shows a "move" cursor icon, make it to default arrow.

**Comment by murugancmi** [comment]
Its drop able error so user know once their cursor move over that.
