### ISSUE TITLE
Callflow_track_webhooks

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#22]
What type of URL, we have to give there ? and by giving url in that field what will happen ? Attached screencast.

![what-url-should-placed](https://user-images.githubusercontent.com/25261710/53339465-707b8c00-392c-11e9-8ef4-bc98b61f9758.png)

**Comment by murugancmi** [comment]
Web hooks is nothing but push notification to server so its require URL(GET method)

**Comment by prabhutelecmi** [comment]
If it is client understandable. then we can close this issue. I think we should give a small note below.

**Comment by murugancmi** [comment]
Webhook have a meaning  same like IVR and team so i can close now
