### ISSUE TITLE
Callflow_track_Can't add team after notify SMS

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#23]
Unable to add team after a notification SMS is placed. Either below or above ?

![team-not-add](https://user-images.githubusercontent.com/25261710/53339671-00213a80-392d-11e9-8ada-5145eea7b8fa.png)

**Comment by murugancmi** [comment]
Flow not allowed after the notification

**Comment by prabhutelecmi** [comment]
IF that is the case. then either we should show a error message.

**Comment by murugancmi** [comment]
there is no drop button , how you can drop its the logic its hidden
