### ISSUE TITLE
Delete Contact Issue

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#24]
Unable to delete the saved contact.
![delete contact](https://user-images.githubusercontent.com/25291469/53339829-6d34d000-392d-11e9-8e58-5c9c51f739f3.png)

**Comment by prasathsekar** [comment]
It is not fixed yet.

**Comment by prasathsekar** [comment]
Contact is deleted, but the contact name is still appearing on the call log.
![issue](https://user-images.githubusercontent.com/25291469/53421673-0fbf8280-3a04-11e9-8c4f-a7d392468491.png)

**Comment by murugancmi** [comment]
in call log it show old call name not in new call
