### ISSUE TITLE
Callflow_track_greetingsms_alone

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#28]
Now i can select and save the call flow for greeting sms alone. Greeting sms alone should not selected.

![greetings-sms-alone-select](https://user-images.githubusercontent.com/25261710/53340226-812d0180-392e-11e9-82e1-019318a0a1fc.png)

**Comment by murugancmi** [comment]
every flow default endpoint is hangup , and at least only one flow is required

**Comment by prabhutelecmi** [comment]
If the user drags only the greeting sms and press the save button, there should be a error message saying "Please select a call flow" should display.

**Comment by murugancmi** [comment]
why they we need show they already added call flow SMS then why we need to show again if they select sms we send only sms then disconnect . This is end user option we need only one flow it may  Notification, SMS or IVR
