### ISSUE TITLE
Addbusinessnumber_popup

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#32]
Spacing required for the whole popup.

![add-business-spacing](https://user-images.githubusercontent.com/25261710/53341763-6fe5f400-3932-11e9-9a1a-2c9830616b74.png)

**Comment by murugancmi** [comment]
What type of issue your facing ?,why you need a space

**Comment by prabhutelecmi** [comment]
Now the spacing is okay. Please leave a space after the comma.
