### ISSUE TITLE
Callflow_track_Change in error message sentence

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#34]
Please change the error message sentence to "You have already registered a hangup setup".

![change-sentence](https://user-images.githubusercontent.com/25261710/53342032-1c27da80-3933-11e9-9489-ce3aa0292ed7.png)

**Comment by prabhutelecmi** [comment]
Please change the error message to "You have already registered a hangup setup" . There is no such word called "setted".

**Comment by murugancmi** [comment]
jsut we can change  "You have already added hangup"

**Comment by prasathsekar** [comment]
Still there is some correction in error message. Kindly change it as "
You have already added hangup"
