### ISSUE TITLE
Call Cost Issue

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#41]
The Billing for my Calls is 0.39p / 30 Secs. But when the call comes and drops between 30secs and 60 Secs the call cost should be 0.78p but it still detucts only 0.39p.
![seconds billing](https://user-images.githubusercontent.com/25291469/53385630-0fdc6580-39a5-11e9-922e-dab55c5127a8.png)
![billing](https://user-images.githubusercontent.com/25291469/53385631-0fdc6580-39a5-11e9-9e3b-69cdb5bc173e.png)

**Comment by murugancmi** [comment]
we are support mins billing now
