### ISSUE TITLE
Recharge Zone Issue

### ISSUE THREAD

**Issue by Ravikumarselvam** [telecmi/telecmi_dashboard_track#45]
When i trying to recharge using our dashboard its not working.
![screenshot 10](https://user-images.githubusercontent.com/25261991/53388483-53d56780-39b1-11e9-91a3-b98a5bc849a1.png)

Next i am going to check balance its showing.
![screenshot 11](https://user-images.githubusercontent.com/25261991/53388527-7cf5f800-39b1-11e9-87b6-6d99f1095714.png)

**Comment by murugancmi** [comment]
Recharge not implemented  @Ravikumarselvam

**Comment by Ravikumarselvam** [comment]
Ok, I close this issue now
