### ISSUE TITLE
Business number_setup

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#46]
I have filled all the required fields, But its still asks me to fill all the details.

![business number](https://user-images.githubusercontent.com/25261710/53388553-94cd7c00-39b1-11e9-930c-962d76e60d69.png)

**Comment by murugancmi** [comment]
please select the state

**Comment by prabhutelecmi** [comment]
If that is the case, we have to indicate state is a required field or we have to show a error message "Please select the state".

**Comment by murugancmi** [comment]
we never say our dashboard this field is required, all form we show only common message .
