### ISSUE TITLE
Business number_setup_required fields

### ISSUE THREAD

**Issue by prabhutelecmi** [telecmi/telecmi_dashboard_track#47]
Please remove two stars(**) in the required fields and make it to one star(*).
Please increase the font size of the state select box and change the color.

![remove star](https://user-images.githubusercontent.com/25261710/53388660-fe4d8a80-39b1-11e9-987f-0a703ecc263d.png)

**Comment by murugancmi** [comment]
Please have a look all our form all select box come with red option

**Comment by murugancmi** [comment]
And please make all business issue in single note and test completely before moving to next task because you are rising one today and another one day after today in same task .Its very difficult to fix

**Comment by murugancmi** [comment]
And in select box default color is red

**Comment by prasathsekar** [comment]
Kindly fix all these issues in the below image.
![address overflow](https://user-images.githubusercontent.com/25291469/53613529-3fd17600-3bfc-11e9-8398-9953802e16eb.png)
![postalcode](https://user-images.githubusercontent.com/25291469/53613530-3fd17600-3bfc-11e9-9ace-b139c4098857.png)

**Comment by murugancmi** [comment]
Issue fixed please check
