### ISSUE TITLE
Upload Music -  (Delete Options Missing)

### ISSUE THREAD

**Issue by Ravikumarselvam** [telecmi/telecmi_dashboard_track#48]
I upload music file wrongly in dashboard, How can i delete the music file.  
![screenshot 12](https://user-images.githubusercontent.com/25261991/53388706-29d07500-39b2-11e9-80f0-cbaa49879744.png)

**Comment by murugancmi** [comment]
There is no delete option in music and its not mandatory to delete ,you just leave that music and upload new one and use it
