### ISSUE TITLE
Call Details Export Issue

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#50]
When i tried to export the call details log. The time displayed in the csv file is incorrect.
![welcome telecmi 4](https://user-images.githubusercontent.com/25291469/53404600-04586100-39dc-11e9-9739-43e6907ae3a5.png)
![screenshot from 2019-02-26 15-31-43](https://user-images.githubusercontent.com/25291469/53404608-1c2fe500-39dc-11e9-85ac-d813b911f151.png)

**Comment by murugancmi** [comment]
Issue fixed in production
