### ISSUE TITLE
Replacing Name Agent as User

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#51]
when i try to add user, delete user. And in Still some of the places it shows agent. Kindly see the below images.
![user adding](https://user-images.githubusercontent.com/25291469/53410893-21486080-39eb-11e9-8245-dd3e8edc84c6.png)
![agent add](https://user-images.githubusercontent.com/25291469/53410894-21486080-39eb-11e9-886a-4768e9bb1a0c.png)
![agent delete](https://user-images.githubusercontent.com/25291469/53410896-21e0f700-39eb-11e9-8711-023dcb28a368.png)

**Comment by prasathsekar** [comment]
Issue not fixed need to update in one more place.
![12](https://user-images.githubusercontent.com/25291469/53421115-1ac5e300-3a03-11e9-93e0-9986af8bb71f.png)

**Comment by murugancmi** [comment]
Please check now
