### ISSUE TITLE
Date filter Issue in activity

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#52]
i have filtered the, from and to date for the past day and it shows the present day details also.
![welcome telecmi 5](https://user-images.githubusercontent.com/25291469/53411924-e09e1680-39ed-11e9-92a5-8f85ac04fb73.png)

**Comment by prasathsekar** [comment]
No it is not fixed.

**Comment by murugancmi** [comment]
Please check now
