### ISSUE TITLE
Disable Contact Icon

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#54]
I saved a number into my contact, and then when i click the more option it still shows add contact icon. Whether it Should be disabled or Update contact icon should be available.
![welcome telecmi 6](https://user-images.githubusercontent.com/25291469/53422810-2e267d80-3a06-11e9-87b7-e09a0d7d0d4f.png)

**Comment by murugancmi** [comment]
issue fixed in stage
