### ISSUE TITLE
Log Issue User Deleted

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#55]
When the user is deleted, the user id is displayed in both incoming and outgoing call log.
![13](https://user-images.githubusercontent.com/25291469/53463049-e0dcf700-3a6b-11e9-9c92-ae15648bcd50.png)
![14](https://user-images.githubusercontent.com/25291469/53463054-e3d7e780-3a6b-11e9-9ada-7462cb99e9cd.png)

**Comment by murugancmi** [comment]
Please check in stage
