### ISSUE TITLE
Office_Timing Issue

### ISSUE THREAD

**Issue by prasathsekar** [telecmi/telecmi_dashboard_track#8]
When i select the country in the time zone. i could not able to change the other timezone from the drop down. If i tried to change it, the selecting countries are added in the time zone
![office_timing_time_zone](https://user-images.githubusercontent.com/25291469/52988957-625ad680-3427-11e9-9a0f-cb07a7e2b7e2.png)

**Comment by murugancmi** [comment]
please check in stage
